### ISSUE TITLE
Port proofs from Go to Rust

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#1]
- [x] feistel: https://github.com/filecoin-project/go-proofs/tree/master/crypto/feistel
- [x] merklepor: https://github.com/filecoin-project/go-proofs/blob/master/por/merklepor/merklepor.go
- [x] proofs interface: https://github.com/filecoin-project/go-proofs/tree/master/proofs
- [ ] snark wrapper: https://github.com/filecoin-project/go-proofs/blob/master/snarkwrapper/snarkwrapper.go
- [x] layerdrgporep
- [x] drgporep

---

DO NOT MOVE:
- merkle tree implementation
- sloth (for now)
- mimc (for now)
- post, batchedpost & fam
