### ISSUE TITLE
Interop between vanilla and snarks

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#12]
Goal: Write tests for circuits that use drgporep.Prove as input and merklepor.Prove as input

- [x] Use Pedersen commitments in vanilla #7
- [x] Use the same KDF #8 
- [x] Merkle Proof format should be the same #16 
- [x] Moving circuit code into rust proofs https://github.com/filecoin-project/rust-proofs/pull/13
- [x] Turning byte slices into Fp
