### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#123]
As @nicola and @porcuquine discussed, this Epic will be used to adjust and sort high-priority project items. Initially, this will be @nicola's handle on priority adjustment, but the eventual intended function is that it be a project-wide tool not necessarily managed by or sourced from @nicola.

High-priority issues should be added to the Epic (right sidebar on ZenHub) so they can be easily identified. When issues are added or priorities changed, a descriptive comment should be added with appropriate people @mentioned. Let's also agree to post a notification in Slack, to minimize risk of changes going unnoticed.

Let's try to use the P0-4 scale (courtesy of @phritz – we should have some communal and canonical definition of these somewhere too, eventually):

P0 - stop what you are doing and address this, shit is on fire and people are dying
P1 - address this with high priority at your next opportunity; something important is blocked
P2 - address this when you have time
P3 - address this if you have time

---
### P0
---
### P1
---
### P2
- [ ] Find running times for replicate on 1GB, 10GB, 100GB, 1TB sectors
  - [x] Short-term memory improvements (#124)
  - [x] In-place disk replication: running replicate currently takes too much memory for larger sizes (without including proof generation), replicate must support disk. [I'm marking this done since we CAN replicate on disk now. There may be a surviving issue, but it should be rephrased/refined – perhaps in its own issue where requirements and tradeoffs can be discussed.]
---
### P3
  - [ ] How long does witness generation take when we store part of the merkle tree (figure out whether we should store merkle trees or computation history of the merkle tree)? (see https://github.com/filecoin-project/rust-proofs/issues/124)
- [ ]  Example for Sloth in circuit (basically https://github.com/filecoin-project/rust-proofs/pull/106 but in a circuit for decode)
---
