### ISSUE TITLE
Add CUDA support

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs#1490]
This is a tracking issue for having full CUDA support.

Several components need to gain CUDA support, on the lowest level it's https://github.com/filecoin-project/rust-gpu-tools, then https://github.com/filecoin-project/bellperson, which are both also used by https://github.com/filecoin-project/neptune/.

 - [x] Finish CUDA optimizations for `ff-cl-gen`: https://github.com/filecoin-project/ff-cl-gen/pull/2
 - [x] Add CUDA support to `rust-gpu-tools`: https://github.com/filecoin-project/rust-gpu-tools/pull/44
 - [x] Add CUDA support to `bellperson`: https://github.com/filecoin-project/bellperson/issues/207 https://github.com/filecoin-project/bellperson/pull/218
 - [x] ~(not strictly needed, but less code, less bugs) Remove 64-bit limb support: https://github.com/filecoin-project/ff-cl-gen/issues/4~ we keep supporting 64-bit limbs on OpenCL.
 - [x] Add CUDA support to Neptune: https://github.com/filecoin-project/neptune/issues/104 https://github.com/filecoin-project/neptune/pull/109

**Comment by vmx** [comment]
Done with the merge of https://github.com/filecoin-project/rust-fil-proofs/pull/1504 :tada:
