### ISSUE TITLE
Next Proofs Release (v10.0.0)

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/rust-fil-proofs#1494]
### Description

Target Sept 30.

PRs targeting the next proofs release (`v10.0.0`):

- [x] Migrate to upstream ff: https://github.com/filecoin-project/rust-fil-proofs/issues/1429
- [x] Requires: https://github.com/filecoin-project/bellperson/pull/205
- [x] Drop pairing and use upstream dependencies: https://github.com/filecoin-project/rust-fil-proofs/pull/1488
- [x] Add CUDA support: https://github.com/filecoin-project/rust-fil-proofs/issues/1490
- [x] Performance improvements for proving*: https://github.com/filecoin-project/bellperson/issues/220
- [x] https://github.com/filecoin-project/rust-fil-proofs/pull/1507
- [x] https://github.com/filecoin-project/rust-fil-proofs/pull/1509

`*` _Possibly this release cycle_

No longer happening in this cycle:

- [ ] Single partition vanilla proof generation and PoSt*: https://github.com/filecoin-project/rust-fil-proofs/pull/1497
- [ ] Improve multicore SDR*: https://github.com/filecoin-project/rust-fil-proofs/pull/1501 [Reverted]
- [ ] Review and test Zondax scheduler: https://github.com/filecoin-project/rust-fil-proofs/pull/1460

### Acceptance criteria

Take stock of where we are on Sept 30 and determine what's reasonable for the release timeframe.

### Risks + pitfalls

Hard deadline is Oct 1, in order to make it into the next lotus release cycle.

**Comment by cryptonemo** [comment]
https://github.com/filecoin-project/rust-fil-proofs/issues/1429

**Comment by dignifiedquire** [comment]
https://github.com/filecoin-project/rust-fil-proofs/issues/1490

**Comment by dignifiedquire** [comment]
- https://github.com/filecoin-project/bellperson/pull/217
- https://github.com/filecoin-project/bellperson/pull/219
- https://github.com/filecoin-project/bellperson/pull/216/bellperson/pull/216)
