### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#150]
### Deadlines

> A clean draft of a commit on 29 September [sounds good], with incremental changes to follow that could be rolled back if absolutely necessary. Final commits should be Oct 5.
– @mishmosh 

[Filecoin alpha feature definition](https://docs.google.com/document/d/1N6JPZckm3ji4FCo5HZjolK7U4G62FJrwT3aRRF3DUb8/edit)
[Filecoin Proofs Glossary](https://docs.google.com/document/d/1jB2cEuwDIYX-duBc-JmP9YgWGqNpshEDlE6c5bSRIoc/edit)
[Proofs Alpha Battle Plan](https://docs.google.com/document/d/1kLfjWU57el0UECSOzvQmgXpVjpGZtpACZz11TQpn_r4/edit#heading=h.78ncj25pktgl)
[Performance Matrix](https://docs.google.com/spreadsheets/d/1StWXZNm-nODNvUxNwXyyd156Bx7G3xcVoX73CSwm_VY/edit#gid=0)

### Notes
Alpha sector size will be 1GB. Operations will be real or mocked to make this true.

### Priority levels
- [1] First
- [2] In-between
- [3] Last

### Outstanding assignments (keep this up-to-date):
 - @nicola: 2
 - @dignifiedquire: 3
 - @laser: 0
 - @porcuquine: 2

### Filecoin Proving System (FPS) API
 - [x] [design-doc][2] Update design doc. @porcuquine #174
#### PoRep
 - [x] [dev-rust][1] Seal outputs commR, commD and a proof (mocked if not practical). (VerifySeal works.) @porcuquine #152
 - [x] [dev-rust][1] GetUnseal: Real API to retrieve original data from sealed data (maybe mocked). @laser #153

#### PoST
 - [ ] [dev-rust][1] Real API with mocked (with simple merklepor) implementation plus handling faults. (VerifyPoST works.) @dignifiedquire #155

#### ZigZag PoRep
 - [x] [dev-rust][3] Use real CommR in circuit. @porcuquine #205

#### PoST
 - [ ] [dev-rust][3] Use single merklepor circuit for mock. https://github.com/filecoin-project/rust-proofs/issues/193 @dignifiedquire 

### Sector Base
 - [x] [dev-rust][3] `write_unsealed` adds node padding. @porcuquine #164
 - [x] [dev-rust][3] `get_unsealed_range` removes node padding. @porcuquine #165
 - [x] [dev-rust][3] make `SyncFile` work with node padding. @laser #166
 - [x] [design-doc][2] Design doc is streamlined to brief description of long-term and short-term (alpha) plans; API snapshot; and diagram or verbal explanation of relationship with both FPS and go-filecoin. @porcuquine #167
 - [x] [design-doc][3] Rename or accept current naming - AND explain it well. @dignifiedquire 

### Filecoin
 - [x] [dev-go][1] StorageMinerClient writes directly to unsealed sector (~no DAG store~). @dignifiedquire 
 - [x] [dev-go][1] StorageRetrievalClient reads directly from sealed sector (~no DAG store~). @laser  

### Risk Mitigation
 - [ ] [research-investigate][1] Capture design plan for PoST vanilla and circuit. @nicola #158
 - [ ] [dev-investigate][1] How to make circuits practical with 200 challenges. @nicola #157
 - [ ] [paper-support][2] Estimate how long it takes to run ZigZag with real parameters (200 challenges, 10 layers, degree 10, expansion degree 6). @dignifiedquire #168
 - [ ] [design-doc][2] Design Doc: ZigZag – emphasize resolving open questions. @porcuquine #163
### Outward-Facing
 - [ ] [spec][3] DrgPorep circuit spec. @porcuquine #154
