### ISSUE TITLE
SDR Empty Sector Update Proof

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [filecoin-project/rust-fil-proofs#1503]
### Description

Add functionality for updating empty (i.e. "CC") SDR sectors to `rust-fil-proofs`.

### Tasks

- [x] merge @DrPeterVanNostrand and @cryptonemo's source branches into a shared codebase
- [x] (vanilla) replica encoding/decoding/remove
- [x] (vanilla) challenge generation (with bucketing)
- [x] (vanilla) API for retrieving apex leafs (private params)
- [x] (circuit) apex-tree gadget
- [x] (circuit) compound-tree `por_no_challenge_input` gadget
- [x] (circuit) empty-sector-update circuit
- [x] `CompoundProof` API for vanilla-circuit interaction (fit to interface)
- [x] lifecycle tests (all sector-sizes and tree shapes): generate seal, encode data, prove, decode data, prove, remove data, prove

**Comment by cryptonemo** [comment]
Ongoing and related work:

https://github.com/filecoin-project/rust-fil-proofs/pull/1519

https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/64

https://github.com/filecoin-project/filecoin-ffi/pull/208
