### ISSUE TITLE
The Great Benchmarks

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#221]
There are many benchmarks to be run, to understand the exact issues we currently have in terms of performance (speed and space). 

## Full Execution

In these benchmarks the goal is to measure the full cycle of

- parameter generation
- replication
- proving
- verifying

parametrized over

- Sector Size,
- Sloth Rounds,
- Number of Challenges, and
- OnDisk vs InMemory.

The values we are interested in in measuring are:

- Total Running Time
  - overall
  - per component
- Memory Usage
  - overall
    - median
    - max usage
  - per component
    - median
    - max usage
- CPU Usage
  - overall
    - median
    - max usage
  - per component
    - median
    - max usage
- Parameter Size on Disk

The initial parameters we will look at should be

| Parameter    | Values                                                                   |
|--------------|--------------------------------------------------------------------------|
| Sector Size  | `32MB`, `64MB`, `128MB`, `256MB`, `512MB`, `1GB`, `10GB`, `20GB`, `32GB` |
| Sloth Rounds | `0`, `1`                                                                 |
| # Challenges | `1`, `10`, `25`, `50`, `100`, `200`                                      |

## Individual Components

These will be implemented as regular [criterion.rs](https://github.com/japaric/criterion.rs) benchmarks in the  `storage-proofs` package.

- [x] Hash functions (Circut & Non Circuit)
  - [x] Pedersen #222
  - [x] SHA256 #222
  - [x] Blake2s 256 #222
- [ ] Merkle Tree Generation
  - [ ] Pedersen
  - [ ] SHA256
  - [ ] Blake2s 256
- [ ] Sloth (Circut & Non Circuit)
- [x] Circuit: Merkle por
  - [x] Pedersen
  - [ ] SHA256
  - [x] Blake2s 256

---

## The Results

I will update this issue with results as they come in 

- memory was measured using `time -v`
- compiled with  `release` flag

### `drgporep-vanilla`

Code based on 7dc4cc1d57122350edd2c63eec1164cdd5f3e993

| hasher | sloth | m | name | size | proving | verifying | max resident set size (kbytes) | replication |
|--------|-------|---|------|------|---------|-----------|--------------------------------|-------------|
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `1 MB` | `0.000215511s` | `0.004197584s` | `14376` | `7.587668102s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `1 MB` | `0.00000457s` | `0.000031813s` | `8792` | `50.334473ms` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `1 MB` | `0.000004931s` | `0.000070801s` | `8216` | `78.473903ms` |
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `64 MB` | `0.000216002s` | `0.0058464s` | `355916` | `482.11625933s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `64 MB` | `0.000007862s` | `0.000070228s` | `350176` | `2.372645499s` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `64 MB` | `0.000007021s` | `0.000126779s` | `351024` | `3.792904305s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `128 MB` | `0.00021918s` | `0.00621437s` | `699892` | `963.951407102s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `128 MB` | `0.000009443s` | `0.00008376s` | `695284` | `4.788106303s` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `128 MB` | `0.000008347s` | `0.000156506s` | `694840` | `7.590049076s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `256 MB` | `0.000219752s` | `0.006494751s` | `1389524` | `1927.997784482s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `256 MB` | `0.000007877s` | `0.0000759s` | `1383296` | `9.748800913s` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `256 MB` | `0.000004857s` | `0.000088669s` | `1383212` | `15.352276015s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `512 MB` | `0.000219909s` | `0.006767565s` | `2766236` | `3859.250779562s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `512 MB` | `0.000008579s` | `0.000086327s` | `2759072` | `19.837990526s` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `512 MB` | `0.000007266s` | `0.000147992s` | `2759136` | `31.41316066s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla` | `1 GB` | `0.000216237s` | `0.006911244s` | `5517892` | `7720.011185162s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla` | `1 GB` | `0.000008422s` | `0.000084538s` | `5511576` | `40.361829327s` |
| `sha256` | `0` | `6` | `drgporep-vanilla` | `1 GB` | `0.00000804s` | `0.000163735s` | `5510912` | `62.765206139s` |

### `drgporep-vanilla-disk`

| hasher | sloth | m | name | size | proving | verifying | max resident set size (kbytes) | replication |
|--------|-------|---|------|------|---------|-----------|--------------------------------|-------------|
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `1 MB` | `0.000224418s` | `0.004292574s` | `15100` | `7.631843627s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `1 MB` | `0.000004591s` | `0.000032713s` | `8528` | `46.815362ms` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `1 MB` | `0.000008728s` | `0.000119361s` | `8680` | `72.391411ms` |
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `64 MB` | `0.00022333s` | `0.00592914s` | `370432` | `482.77419811s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `64 MB` | `0.00000718s` | `0.000060596s` | `364936` | `2.417458081s` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `64 MB` | `0.000008063s` | `0.000136628s` | `364432` | `3.798658039s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `128 MB` | `0.000221125s` | `0.006167417s` | `732660` | `965.576507161s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `128 MB` | `0.000008216s` | `0.000074128s` | `725084` | `4.84231904s` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `128 MB` | `0.000008699s` | `0.000152945s` | `725420` | `7.652530109s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `256 MB` | `0.000218477s` | `0.006447437s` | `1453220` | `1931.901478256s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `256 MB` | `0.000004802s` | `0.00004302s` | `1446312` | `9.900098656s` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `256 MB` | `0.000004786s` | `0.000086245s` | `1445840` | `15.47019121s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `512 MB` | `0.000221569s` | `0.006688682s` | `2894440` | `3867.815452415s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `512 MB` | `0.000008135s` | `0.000075722s` | `2887752` | `20.108807588s` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `512 MB` | `0.000005618s` | `0.000100057s` | `2888392` | `31.339301327s` |
| `pedersen` | `0` | `6` | `drgporep-vanilla-disk` | `1 GB` | `0.000221889s` | `0.006990621s` | `5777820` | `7736.014012276s` |
| `blake2s` | `0` | `6` | `drgporep-vanilla-disk` | `1 GB` | `0.000007231s` | `0.000066522s` | `5772204` | `41.062445339s` |
| `sha256` | `0` | `6` | `drgporep-vanilla-disk` | `1 GB` | `0.000008895s` | `0.000165408s` | `5771572` | `63.888468621s` |

### `merklepor - pedersen`

| chllgs | sloth | m | name | size | proving | verifying | params gen | max resident set size (kbytes) |
|------------|-------|---|------|------|---------|-----------|------------|--------------------------------|
| `1` | `0` | `6` | `merklepor` | `1 MB` | `0.251605376s` | `0.004905556s` | `1.413948383s` | `57764` |
| `1` | `0` | `6` | `merklepor` | `64 MB` | `0.278677928s` | `0.00471867s` | `1.770992373s` | `72436` |
| `1` | `0` | `6` | `merklepor` | `128 MB` | `0.282813112s` | `0.005612408s` | `1.818666812s` | `70960` |
| `1` | `0` | `6` | `merklepor` | `256 MB` | `0.284097937s` | `0.004781583s` | `1.863152437s` | `70128` |
| `1` | `0` | `6` | `merklepor` | `512 MB` | `0.383436983s` | `0.003915707s` | `2.274921424s` | `94596` |
| `1` | `0` | `6` | `merklepor` | `1 GB` | `0.389716608s` | `0.003424464s` | `2.320927896s` | `97900` |
| `10` | `0` | `6` | `merklepor` | `1 MB` | `1.435045417s` | `0.008877994s` | `11.326219538s` | `374980` |
| `10` | `0` | `6` | `merklepor` | `64 MB` | `2.265698772s` | `0.008109409s` | `17.351892486s` | `545252` |
| `10` | `0` | `6` | `merklepor` | `128 MB` | `2.317363322s` | `0.005262446s` | `17.937112824s` | `566036` |
| `10` | `0` | `6` | `merklepor` | `256 MB` | `2.343732175s` | `0.01300441s` | `18.666477593s` | `580240` |
| `10` | `0` | `6` | `merklepor` | `512 MB` | `2.431120432s` | `0.006914848s` | `19.143903995s` | `561716` |
| `10` | `0` | `6` | `merklepor` | `1 GB` | `2.453912662s` | `0.006917054s` | `19.728219744s` | `577348` |
| `50` | `0` | `6` | `merklepor` | `1 MB` | `7.934670701s` | `0.013270547s` | `64.723093568s` | `1863324` |
| `50` | `0` | `6` | `merklepor` | `64 MB` | `9.095776743s` | `0.020186518s` | `81.235600515s` | `2305980` |
| `50` | `0` | `6` | `merklepor` | `128 MB` | `9.296591319000001s` | `0.017429871s` | `83.530248731s` | `2383224` |
| `50` | `0` | `6` | `merklepor` | `256 MB` | `9.401865024s` | `0.016311637s` | `85.753596425s` | `2455184` |
| `50` | `0` | `6` | `merklepor` | `512 MB` | `9.518330912s` | `0.016206423s` | `88.2653105s` | `2528680` |
| `50` | `0` | `6` | `merklepor` | `1 GB` | `9.838261719s` | `0.014633421s` | `91.073613007s` | `2602292` |
| `100` | `0` | `6` | `merklepor` | `1 MB` | `15.147319677s` | `0.024805531s` | `127.740123965s` | `3705316` |
| `100` | `0` | `6` | `merklepor` | `64 MB` | `17.109633192s` | `0.03077063s` | `160.147724335s` | `4586324` |
| `100` | `0` | `6` | `merklepor` | `128 MB` | `17.561282191s` | `0.029774745s` | `164.825718431s` | `4735816` |
| `100` | `0` | `6` | `merklepor` | `256 MB` | `17.820356894s` | `0.029496434s` | `169.77700281s` | `4882244` |
| `100` | `0` | `6` | `merklepor` | `512 MB` | `18.4906566s` | `0.027632351s` | `174.892743959s` | `5029240` |
| `100` | `0` | `6` | `merklepor` | `1 GB` | `18.701751723s` | `0.025517065s` | `180.110792878s` | `5177700` |
| `200` | `0` | `6` | `merklepor` | `1 MB` | `29.323784347s` | `0.046262595s` | `252.77631944s` | `7381272` |
| `200` | `0` | `6` | `merklepor` | `64 MB` | `33.795633755s` | `0.050569527s` | `317.095339678s` | `9145024` |
| `200` | `0` | `6` | `merklepor` | `128 MB` | `34.475973969s` | `0.04764678s` | `331.459761769s` | `9441316` |
| `200` | `0` | `6` | `merklepor` | `256 MB` | `34.891317633s` | `0.055173572s` | `342.206911109s` | `9735252` |
| `200` | `0` | `6` | `merklepor` | `512 MB` | `35.911065563s` | `0.049799713s` | `352.501355508s` | `10031904` |
| `200` | `0` | `6` | `merklepor` | `1 GB` | `36.840972135s` | `0.053122645s` | `364.13747801s` | `10329512` |

### merklepor - blake2s

| name      | size  | proving              | verifying           | params gen     | replication | max resident set size | challenges | size  | sloth | m |
|-----------|-------|----------------------|---------------------|----------------|-------------|-----------------------|------------|-------|-------|---|
| merklepor | 1 kB  | 1.092311481 seconds  | 0.006180149 seconds | 15.856068591s  |             | 375032                | 1          | 1     | 0     | 6 |
| merklepor | 1 MB  | 3.619487629 seconds  | 0.005975654 seconds | 50.164147114s  |             | 1060996               | 1          | 1024  | 0     | 6 |
| merklepor | 32 MB | 3.726699581 seconds  | 0.005442349 seconds | 62.371090569s  |             | 1308920               | 1          | 32768 | 0     | 6 |
| merklepor | 1 kB  | 1.978509514 seconds  | 0.007020025 seconds | 31.369645427s  |             | 649408                | 2          | 1     | 0     | 6 |
| merklepor | 1 MB  | 6.791187019 seconds  | 0.010004603 seconds | 99.57827673s   |             | 2034892               | 2          | 1024  | 0     | 6 |
| merklepor | 32 MB | 7.03828934 seconds   | 0.009190803 seconds | 124.099877802s |             | 2509612               | 2          | 32768 | 0     | 6 |
| merklepor | 1 kB  | 6.614156842 seconds  | 0.010669766 seconds | 87.152731646s  |             | 1815056               | 5          | 1     | 0     | 6 |
| merklepor | 1 MB  | 13.216271451 seconds | 0.010530041 seconds | 235.816505759s |             | 4703296               | 5          | 1024  | 0     | 6 |
| merklepor | 32 MB | 24.899177035 seconds | 0.005776601 seconds | 347.259922485s |             | 7182904               | 5          | 32768 | 0     | 6 |

### DrgPoRep

| challenges | sloth | m | name | size | proving | verifying | max resident set size (kbytes) | params gen |
|------------|-------|---|------|------|---------|-----------|--------------------------------|------------|
| `1` | `0` | `6` | `drgporep` | `1 MB` | `1.311725842s` | `0.000000074s` | `327904` | `9.77518193s` |
| `1` | `0` | `6` | `drgporep` | `64 MB` | `1.501762851s` | `0.000000127s` | `394104` | `12.358297564s` |
| `1` | `0` | `6` | `drgporep` | `128 MB` | `1.524572315s` | `0.000000119s` | `406540` | `12.807208843s` |
| `1` | `0` | `6` | `drgporep` | `256 MB` | `2.215791609s` | `0.000000123s` | `507444` | `16.044048407s` |
| `1` | `0` | `6` | `drgporep` | `512 MB` | `2.211980433s` | `0.000000079s` | `519588` | `16.545981219s` |
| `1` | `0` | `6` | `drgporep` | `1 GB` | `2.243622957s` | `0.000000111s` | `531408` | `16.875194012s` |
| `10` | `0` | `6` | `drgporep` | `1 MB` | `9.817739837s` | `0.000000118s` | `2577692` | `91.001459883s` |
| `10` | `0` | `6` | `drgporep` | `64 MB` | `15.732048984s` | `0.000000134s` | `3987508` | `139.273301446s` |
| `10` | `0` | `6` | `drgporep` | `128 MB` | `16.021252269s` | `0.000000134s` | `4099128` | `144.437478819s` |
| `10` | `0` | `6` | `drgporep` | `256 MB` | `16.4044488s` | `0.000000103s` | `4220148` | `148.094921758s` |
| `10` | `0` | `6` | `drgporep` | `512 MB` | `16.574096686s` | `0.000000101s` | `4330388` | `152.84327677s` |
| `10` | `0` | `6` | `drgporep` | `1 GB` | `17.012658384s` | `0.000000103s` | `4452068` | `157.899858234s` |
| `50` | `0` | `6` | `drgporep` | `1 MB` | `57.870287902s` | `0.000000099s` | `14840944` | `523.051451256s` |
| `50` | `0` | `6` | `drgporep` | `64 MB` | `66.744366845s` | `0.000000131s` | `18392448` | `654.192718803s` |
| `50` | `0` | `6` | `drgporep` | `128 MB` | `68.09091595s` | `0.000000107s` | `19002280` | `675.476496231s` |
| `50` | `0` | `6` | `drgporep` | `256 MB` | `68.841213136s` | `0.000000123s` | `19574864` | `696.706183834s` |
| `50` | `0` | `6` | `drgporep` | `512 MB` | `70.603506653s` | `0.000000116s` | `20167380` | `718.8787389s` |
| `50` | `0` | `6` | `drgporep` | `1 GB` | `72.354635564s` | `0.00000012s` | `20764124` | `735.422197837s` |

####  Parameter Sizes
- `m: 6`
- `sloth: 0`

| Data Size | Challenges | Parameter Size |
|-----------|------------|----------------|
| `1MB` | `1` | ` 78M` |
| `1MB` | `10` | `726M` |
| `1MB` | `50` | `4,2G` |
| `1MB` | `100` | `8,3G` |
| `64MB` | `1` | ` 98M` |
| `64MB` | `10` | `1,1G` |
| `64MB` | `50` | `5,1G` |
| `64MB` | `100` | `11G` |
| `128MB` | `1` | `101M` |
| `128MB` | `10` | `1,2G` |
| `128MB` | `50` | `5,3G` |
| `128MB` | `100` | ` 11G` |
| `256MB` | `1` | `128M` |
| `256MB` | `10` | `1,2G` |
| `256MB` | `50` | `5,4G` |
| `256MB` | `100` | `11G` |
| `512MB` | `1` | `132M` |
| `512MB` | `10` | `1,2G` |
| `512MB` | `50` | `5,6G` |
| `1GB` | `1` | `135M` |
| `1GB` | `10` | `1,3G` |
| `1GB` | `50` | `5,8G` |
