### ISSUE TITLE
rust-proofs SectorBuilder writes entirety of piece-data to staging sector in one shot

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#252]
## TODO

- [ ] compute cid of piece-bytes within sector builder
- [ ] wire up get-next-sector-id
- [ ] return correct sector-id

## OPEN QUESTIONS

- [ ] should we accept a cid and piece size from FFI consumers? if so: do we validate inbound bytes against those values?
