### ISSUE TITLE
Implement a better branching and release flow for rust-fil-proofs

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs#507]
### Description

go-filecoin depends on rust-fil-proofs as a submodule. rust-fil-proofs is "released" by updating the submodule SHA in go-filecoin. This has worked reasonably well so far, but may present problems in the future:

Suppose that a deploy happens when the head rust-fil-proofs `master` is at SHA 1. A few days go by and now the head of rust-fil-proofs `master` is at SHA 10. A regression is detected in SHA 1, necessitating a hotfix. A rust-fil-proofs developer merges the hotfix into rust-fil-proofs `master` at SHA 11. go-filecoin wants this patch, but changing the submodule SHA from 1 to 11 means that commits 2..10 are also released. Releasing commits 2..11 is more risky (from a regression standpoint) than releasing commit 11.

We need to design a process by which we are deliberate in releasing rust-fil-proofs code to go-filecoin.

My current thought is to create a `production` branch off of rust-fil-proofs `master`, and a release involves cherry picking commits from `master` into `production`. go-filecoin would be modified to point at a `production` SHA instead of `master`.

**Comment by porcuquine** [comment]
That's probably the simplest of available options, so let's give it a try.

I think we should probably try to reset `production` to `master` for each 'major' release (however that comes to be defined), rather than trying to keep a long-running parallel branch which never reconverges. But at any given time it should be easy to create an incremental release to `production` without having to understand or accept other intervening changes to master. (And, by the same token, changes merged to master should not be saddled with the burden of ensuring they are suitable for inclusion in an immediate hotfix/integration-related release that needs to happen short-term.)

**Comment by dignifiedquire** [comment]
Why not use the proposed solution from #489 and use tags for this? having multiple branches is pretty tricky and error prone in my experience

**Comment by dignifiedquire** [comment]
we can always do specific branches for hotfixes if it comes to that

**Comment by laser** [comment]
> Why not use the proposed solution from #489 and use tags for this? having multiple branches is pretty tricky and error prone in my experience

I don't actually know how the "publish to crates.io" proposal relates to the way that go-filecoin consumes rust-fil-proofs. I want to know, though. Will you help me know, @dignifiedquire?

**Comment by porcuquine** [comment]
I don't have strong feelings about what we *try* first. I think we need to be open to adjustment in the face of what works and doesn't. The one thing I would say about the tags route is that it doesn't leave room for the (possibly) common case in which we want our intermittent release to contain only certain of the recent added changes. That's fine… we can create a release branch — but if that's where we'll end up, might be easier to start there. A lot of this will depend on development patterns which are a bit unknown right now as integration accelerates — while a lot of work on scaling also needs to happen.

**Comment by dignifiedquire** [comment]
My main goal with that is to get a "proper" release process, rather than any commit goes. The nice thing about crates release is that we could possibly use `cargo install proofs` as well has use the tagged release to pull specific versions known/expected to be working. But in regards to hotfixes I guess we need to use a different branch, ah well..

**Comment by pooja** [comment]
Jumping in here to add my .02 that having a more defined release process will be useful and extremely helpful for inter-WG coordination. It should also allow for even more independence between rust-fil-proofs and go-filecoin without spawning any negative consequences that such independence could otherwise introduce. 

Would +1 having something implemented to try it out before EOQ2, and adjusting as needed. You're all the experts here, but wanted to flag this as something that seems more useful now than it maybe did 2 months ago!

**Comment by dignifiedquire** [comment]
I would like to start approach of using crates.io releases + github tags with bumping the versions for releases going forward. 

For now I can take on the burden of doing the manual work of doing them. 

To get to this state, the following is needed

- [ ] get buy in from 
  - [ ] @porcuquine 
  - [ ] @laser 
  - [ ] @schomatis 
  - [ ] @sidke 
- [ ] publish all our git dependencies to crates.io (@dignifiedquire)
- [ ] publish initial version of our crates to crates.io + git tag + version bump (@dignifiedquire)

**Comment by laser** [comment]
@dignifiedquire - This sounds great. Would you please describe (in this issue is fine) your proposed release workflow? 

I have two desires:

1. I want to know how to release rust-fil-proofs using this new workflow
2. I want to understand the work required to ensure that the new workflow doesn't break the go-filecoin integration

**Comment by dignifiedquire** [comment]
>     1. I want to know how to release rust-fil-proofs using this new workflow

this will likely involve the following
- having an account on crates.io that is authorized to publish the relevant crates
- triggering a release script that does the work
- profit

> I want to understand the work required to ensure that the new workflow doesn't break the go-filecoin integration

I imagine the following workflow

- go-filecoin __only__ uses tagged release or versions published from crates.io (depending on what is easier to work with)
- before cutting a new release, the current `master` is tested with go-filecoin 
- if this is fine, we publish a new release, and go-filecoin can update to that

**Comment by porcuquine** [comment]
I suggest a slight adjustment. Before creating a release, create a new candidate release branch (identical with `master`) and test that with `go-filecoin`. If successful, publish the release from the branch. If we follow that process, we'll never accidentally publish changes which arrived on `master` after the testing began.

**Comment by laser** [comment]
@dignifiedquire thanks for explaining. Also, I like @porcuquine's idea.

A question:

> go-filecoin only uses tagged release or versions published from crates.io (depending on what is easier to work with)

I think what you're saying is that go-filecoin will continue to consume rust-fil-proofs as a submodule. I think what you're saying is that go-filecoin will only use rust-fil-proofs SHAs which correspond to rust-fil-proofs release tags. Is that correct?

**Comment by dignifiedquire** [comment]
>  you're saying is that go-filecoin will only use rust-fil-proofs SHAs which correspond to rust-fil-proofs release tags. Is that correct?

Effectively yes. Ie an update should be `cd submodule-folder && git fetch origin && git checkout vx.y.z && cd ../ && git add . && git commit -m "update rust-fil-proofs to vx.y.z"`

**Comment by laser** [comment]
Sounds like a good plan to me.

**Comment by dignifiedquire** [comment]
Work started, by setting up CI on all these, next step is to rename the crates and publish them, tracking this work here for simplicity:

Forks:

- [ ] ff
- [ ] ff-derive
- [ ] phase2
- [ ] pairing
- [ ] bellman
- [ ] sapling-crypto

Not published deps:
- [ ] blake2s_simd (asked for a publish here: https://github.com/oconnor663/blake2s_simd/issues/1#issuecomment-493419307)

**Comment by schomatis** [comment]
Is [`merkle_light`](https://github.com/filecoin-project/merkle_light`) eligible for that list?

**Comment by dignifiedquire** [comment]
it is, updated, thank you

**Comment by mishmosh** [comment]
When the release cadence & timing are decided, could you announce (and make sure go-filecoin team acks)?

I imagine that rust-fil-proofs releases are offset from go-filecoin's, and go-filecoin's master (and thus, nightly devnet) is manually bumped to the latest rust-fil-proofs release each time. @dignifiedquire confirmed this in a chat.

That will force go-filecoin devs to consume new proofs between releases and allow breaking changes to be discovered earlier --> more peace of mind for both teams.

**Comment by laser** [comment]
@mishmosh 

> I imagine that rust-fil-proofs releases are offset from go-filecoin's, and go-filecoin's master (and thus, nightly devnet) is manually bumped to the latest rust-fil-proofs release each time. 

> That will force go-filecoin devs to consume new proofs between releases and allow breaking changes to be discovered earlier

Yep, you're exactly right. What you describe is precisely what we do today: I bump the version of rust-fil-proofs used by go-filecoin manually.

From go-filecoin's perspective, the only difference between what @dignifiedquire  proposes and what we do now is that instead of go-filecoin consuming an arbitrary Git SHA from rust-fil-proofs `master`, it will consume only blessed release-SHAs.

**Comment by dignifiedquire** [comment]
Tracking the actual publishing here: https://github.com/filecoin-project/rust-fil-proofs/issues/489

**Comment by dignifiedquire** [comment]
we have improved some of the things, which seem to be good enough for now, closing
