### ISSUE TITLE
Implement Piece Inclusion Proof

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/rust-fil-proofs#592]
### Description

Names below are descriptive. Sync with integration effort before finalizing.

The first four items were taken care of in #602 

  - [x] Rename legacy piece inclusion proof to `TrustedPieceInclusionProof`. [#602 renamed but then removed this as no longer relevant.]
  - [x] Implement `compute_comm_p`. [#602 adds `compute_piece_commitment`, `generate_piece_commitment`, and `generate_piece_commitment_bytes` providing various interfaces to `comm_p` generation.]
  - [x] Implement `create_piece_inclusion_proofs` for aligned pieces. [#602 implements `piece_inclusion_proofs`.].
  - [x] Implement `verify_piece_inclusion_proof` for aligned pieces. [#602 `PieceInclusionProof` has a `verify` method.]

---
  - [ ] Extend `verify_piece_inclusion_proof` to handle un-aligned pieces.
  - [ ] Extend `create_piece_inclusion_proofs` to handle un-aligned pieces.
  - [ ] Provide support functions for packing unaligned pieces such that correct piece inclusion proofs can be generated.

Note that for testnet the plan is to only pack aligned pieces. However, we want to be able to verify unaligned pieces to handle the general case of what miners might do.

The goal is to complete the first four items above quickly. With that in place, we should be able to proceed with integration and development as required for the storage market.

The items below the line are desirable but shouldn't affect miners only using our sector-packing code.

**Comment by porcuquine** [comment]
cc @sidke @whyrusleeping @acruikshank @laser

**Comment by dignifiedquire** [comment]
@porcuquine are you still working on this?

**Comment by porcuquine** [comment]
It's paused but will need to be picked up later. The fully aligned PIP is implemented, and the interface should be stable. However, we support neither generating nor verifying un-aligned PIPs. We theoretically intend to support at least verification of unaligned PIPs — but that unfortunately will entail most or all the work of also generating.

I'll unassign myself but probably need to at least be in the loop when the work is restarted.

**Comment by laser** [comment]
This work is complete and integrated with go-filecoin. I'm closing this issue.

Note:

> Extend create_piece_inclusion_proofs to handle un-aligned pieces.

The piece inclusion proof-generating function which we have in the codebase today accepts a list of piece sizes (not yet bit padded and not aligned) and a source file (the staged sector, which is bit padded) and produces an enumeration of piece commitments and corresponding piece inclusion proof. It hides from the caller the fact that we are aligning pieces, and hides from the caller the fact that we bit-pad.

> Extend verify_piece_inclusion_proof to handle un-aligned pieces.

Like the piece inclusion proof-generation function, the verification function accepts a piece size (the number of bytes in the user's piece before bit-padding has been added - does not include alignment), piece commitment, data commitment, sector size, and a piece inclusion proof. It hides from the caller the fact that we are aligning pieces and hides the fact that we also bit-pad.

> Provide support functions for packing unaligned pieces such that correct piece inclusion proofs can be generated.

The `add_piece` function accepts a source file (a place from which the callee can read piece bytes) and a number of bytes-amount in that piece (before bit-padding and without alignment). We hide from the caller the fact that we bit-pad when writing that file to a staged sector, and hide from the caller the fact that we will likely add alignment bytes to the staged sector before or after that piece.
