### ISSUE TITLE
Benchmarks roadmap

### ISSUE THREAD

**Issue by nicola** [filecoin-project/rust-fil-proofs#71]
Note: In parenthesis the parameters that we would like parametrize

- DRGPOREP-VANILLA
	- [x] drgporep.Replicate (size, m, sloth_iter)
	- [x] drgporep.Prove (size, m, sloth_iter)
	- [ ] drgporep.Verify (size, m, sloth_iter)
- DRGPOREP-CIRCUIT (size, m, sloth_iter, number-of-challenges)
  - [x] number of constraints https://github.com/filecoin-project/rust-proofs/pull/70 https://github.com/filecoin-project/rust-proofs/pull/83
  - [x] time to generate witnesses
  - [x] time to generate proof
- MERKLEPOR-CIRCUIT (size, number-of-challenges)
  - [x] number of constraints
  - [x] time to generate witnesses
  - [x] time to generate proof
